name: Go CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      # Configurar Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Descargar el código
      - name: Check out code
        uses: actions/checkout@v3

      # Cache de módulos de Go
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Descargar dependencias
      - name: Get dependencies
        run: go mod download

      # Ejecutar pruebas
      - name: Run tests
        run: go test -v -cover ./tests/...

      # Generar documentación Swagger
      - name: Generate Swagger documentation
        run: swag init -g cmd/api/main.go -o docs

      # Construir el binario
      - name: Build binary
        run: go build -v -o build/vet-clinic-api ./cmd/api/main.go

      # Verificar que el binario existe
      - name: Verify binary exists
        run: ls -l build/vet-clinic-api

      # Subir el binario como artefacto
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: vet-clinic-api
          path: build/vet-clinic-api